name: Update Blocklist

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-blocklist:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Run update script
        run: |
          chmod +x update_blocklist.sh
          ./update_blocklist.sh

        env:
          SOURCE_URL: ${{ secrets.SOURCE_URL }}
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
          KV_NAMESPACE_ID: ${{ secrets.KV_NAMESPACE_ID }}
